print("\t\t\tONLINE APPLICATION FORM")
user_name = input("Enter your Full Name : ")
dob = input("Enter your Date of Birth (In the format :dd/mm/yy) : ")
age = int(input("Enter your age (In the number format) : "))
offered_course = input("Enter the Course that we offered (BCA,B.SC(computer science),B.COM,BBA) : ")
print(f"You have selected the {offered_course} course !")
mail = input("Enter your verified personal E-mail Id (In abc@xyz.com) : ")
country = input("Enter your country Name : ")
language = input("Enter your mother language : ")
phone = input("Enter your mobile number (In the format : country_code your number): ")
print("Enter the address in line by line !")
address = []
for i in range(5):
    address.append(input("Address : "))
for j in address:
    print(j)
print("\n\n")
print("\t\t\t\t APPLICATION FORM")
print("\n")
print(f"\t\t\t NAME            : {user_name}")
print(f"\t\t\t DOB             : {dob}")
print(f"\t\t\t AGE             : {age}")
print(f"\t\t\t COURSE          : {offered_course}")
print(f"\t\t\t E-MAIL          : {mail}")
print(f"\t\t\t COUNTRY         : {country}")
print(f"\t\t\t MOTHER TONGUE   : {language}")
print(f"\t\t\t PHONE           : {phone}")
print(f"\t\t\t HOME ADDRESS    : {address}")
print("\n")
print("\t\t This is your filled application form !")
